require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false
Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/**/*'
    - 'Rakefile'
    - 'config/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*.rb'
    - 'vendor/**/*'
  UseCache: false
  TargetRailsVersion: 6.0
  TargetRubyVersion: 2.6.5
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Layout/DotPosition:
  EnforcedStyle: trailing
Capybara/FeatureMethods:
  EnabledMethods: ['feature', 'scenario', 'xscenario','given', 'background']
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
