Documentation:
  Enabled: false
Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/**/*'
    - 'Rakefile'
    - 'config/**/*'
    - 'bin/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*.rb'
    - 'vendor/**/*'
  UseCache: false
  TargetRailsVersion: 5.2
  TargetRubyVersion: 2.6
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Layout/DotPosition:
  EnforcedStyle: trailing
