version: '3.6'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  server:
    image: skygvinn/alpine-ruby2.6.5-nodejs:v1.3
    container_name: ubs_finder
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=vendor/bundle
      - BUNDLE_DISABLE_SHARED_GEMS=1
    volumes:
      - .:/var/www/ubs_finder:Z
    working_dir: /var/www/ubs_finder
    command: bundle exec rails s -b 0.0.0.0
    depends_on:
      - db
