default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # host: localhost  # when using localhost
  host: db       # when using docker
  username: postgres
  password: postgres

development:
  <<: *default
  database: ubs_finder_development

test:
  <<: *default
  database: ubs_finder_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: ubs_finder_production
  username: ubs_finder
  password: <%= ENV['UBS_finder_DATABASE_PASSWORD'] %>
  pool: 10
